[tool.poetry]
name = "example_pkg"
version = "0.1.0"
description = ""
authors = ["John15321 <janbronicki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mkdocs = "^1.2.3"
flake8 = "^4.0.1"
pylint = "^2.12.2"
black = "^22.1.0"
tox = "^3.24.5"
isort = "^5.10.1"
mkdocs-material = "^8.2.1"
mike = "^1.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
